language: php

php:
  - 5.4
  - 5.5

env:
  global:
    - PLUGIN_NAME=WakaTime
    - CAKE_VERSION=2.4
  matrix:
    - CAKE_VERSION=2.4
    - CAKE_VERSION=2.5
    - CAKE_VERSION=2.6

matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - FOC_VALIDATE=1

before_script:
  - git clone https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh
  - echo "require_once ROOT . '/vendor/autoload.php';" >> Config/bootstrap.php

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
